### ISSUE TITLE
Organize and formalize messy repository structures

### ISSUE THREAD

**Issue by tomoio** [warashibe/next-dapp#58]
Next Dapp repos at the moment are scattered and messy. Organize them in accordance with the new bit based plugin system.

**Comment by tn0ms** [comment]
* [Next Dapp Main Repository](https://github.com/warashibe/next-dapp)
* [Next Dapp CLI Tools](https://github.com/warashibe/nextdapp)
* [Next Dapp Docs](https://github.com/warashibe/next-dapp-docs)
