### ISSUE TITLE
Add contributors section to main repo README

### ISSUE THREAD

**Issue by tomoio** [warashibe/next-dapp#69]
Give them decent credits in the right place.

**Comment by ocrybit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Next Dapp ドキュメント](https://trello.com/c/rMyh5v9i/115-next-dapp-%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88)

**Comment by tn0ms** [comment]
https://github.com/warashibe/next-dapp/commit/51133d0bc56c0eb09d2c2fca75de635197cbdbee
